on: 
  workflow_dispatch:
  pull_request_target:
      types: [opened, labeled, unlabeled, synchronize]

permissions:
  pull-requests: write

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
           python-version: "3.10"
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # checkout all branches
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Show workdirectory after site cloned
        run: |
           pwd
           ls
